name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  ci:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0', '8.1']

    steps:
    - name: Start selenium server with Docker
      run: docker run -d --net=host -v /tmp:/tmp --shm-size="2g" selenium/standalone-firefox

    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Copy c3 to web root
      run: cp -f vendor/codeception/c3/c3.php web/c3.php

    - name: Migration test database
      run: yes | php tests/bin/yii migrate

    - name: Run test server
      run: nohup php -d xdebug.remote_enable=On -d xdebug.mode=coverage tests/bin/yii serve &

    - name: Run test suite
      # fix open csv file permission denied
      run: sudo php -d xdebug.remote_enable=On -d xdebug.mode=coverage vendor/bin/codecept run --coverage --coverage-xml

    - name: Upload coverage result to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        composer require php-coveralls/php-coveralls:^2.5
        vendor/bin/php-coveralls --coverage_clover=tests/_output/coverage.xml --json_path=tests/_output/coveralls-upload.json -v
